### ISSUE TITLE
Latest version of ClashRoyale on PyPI, aiohttp broken

### ISSUE THREAD

**Issue by sayeghr** [cgrok/clashroyale#14]
When I try to import clashroyale, I get the following error:

`(CRActivityBot-LU2alj18) bash-3.2$ python
Python 3.6.5 (default, Apr 29 2018, 09:02:36) 
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import clashroyale
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sayeghr/.local/share/virtualenvs/CRActivityBot-LU2alj18/lib/python3.6/site-packages/clashroyale/__init__.py", line 25, in <module>
    from .client import Client
  File "/Users/sayeghr/.local/share/virtualenvs/CRActivityBot-LU2alj18/lib/python3.6/site-packages/clashroyale/client.py", line 31, in <module>
    import aiohttp
  File "/Users/sayeghr/.local/share/virtualenvs/CRActivityBot-LU2alj18/lib/python3.6/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import *  # noqa
  File "/Users/sayeghr/.local/share/virtualenvs/CRActivityBot-LU2alj18/lib/python3.6/site-packages/aiohttp/client.py", line 15, in <module>
    from . import connector as connector_mod
  File "/Users/sayeghr/.local/share/virtualenvs/CRActivityBot-LU2alj18/lib/python3.6/site-packages/aiohttp/connector.py", line 17, in <module>
    from .client_proto import ResponseHandler
  File "/Users/sayeghr/.local/share/virtualenvs/CRActivityBot-LU2alj18/lib/python3.6/site-packages/aiohttp/client_proto.py", line 6, in <module>
    from .http import HttpResponseParser, StreamWriter
  File "/Users/sayeghr/.local/share/virtualenvs/CRActivityBot-LU2alj18/lib/python3.6/site-packages/aiohttp/http.py", line 8, in <module>
    from .http_parser import (HttpParser, HttpRequestParser, HttpResponseParser,
  File "/Users/sayeghr/.local/share/virtualenvs/CRActivityBot-LU2alj18/lib/python3.6/site-packages/aiohttp/http_parser.py", line 15, in <module>
    from .http_writer import HttpVersion, HttpVersion10
  File "/Users/sayeghr/.local/share/virtualenvs/CRActivityBot-LU2alj18/lib/python3.6/site-packages/aiohttp/http_writer.py", line 304, in <module>
    class URL(yarl.URL):
  File "/Users/sayeghr/.local/share/virtualenvs/CRActivityBot-LU2alj18/lib/python3.6/site-packages/yarl/__init__.py", line 232, in __init_subclass__
    "is forbidden".format(cls))
TypeError: Inheritance a class <class 'aiohttp.http_writer.URL'> from URL is forbidden
>>> 
`

aiohttp version 2.2.5
clashroyale version 3.4.1

Python 3.6.5

**Comment by fourjr** [comment]
Getting this error?
```
TypeError: Inheritance a class <class 'aiohttp.http_writer.URL'> from URL is forbidden
```

This is due to yarl 1.2 having a breaking change that breaks aiohttp. Downgrade your yarl using `pip install -U "yarl<1.2"`

**Comment by sayeghr** [comment]
Shouldn't that dependency requirement be reflected in clashroyales setup.py?

**Comment by fourjr** [comment]
I haven't had the time to do so, you could do a PR if you want. For now, this is the hotfix

**Comment by sayeghr** [comment]
Okay, thank you :)
