### ISSUE TITLE
Install Currently Broken (due to html load 503 error)

### ISSUE THREAD

**Issue by danjump** [cgrok/clashroyale#27]
The install process is currently broken. it's trying to download some settings from a url that is apparently broken. maybe include those setting in the repo to remove this dependancy?

```
Traceback (most recent call last):
  File "setup.py", line 34, in <module>
    data = json.loads(urllib.request.urlopen('https://fourjr-webserver.herokuapp.com/cr/constants').read())
  File "/home/danielj/anaconda3/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/home/danielj/anaconda3/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/home/danielj/anaconda3/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/danielj/anaconda3/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/home/danielj/anaconda3/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/home/danielj/anaconda3/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Unavailable
```

**Comment by fourjr** [comment]
Try again next month. Something went wrong on my end :(

**Comment by rodelfard** [comment]
https://prnt.sc/l0fds6

:'(

**Comment by fourjr** [comment]
![image](https://user-images.githubusercontent.com/28086837/46257290-c6691680-c4e9-11e8-816e-8bd4b3b318b6.png)

**Comment by fourjr** [comment]
back up
