### ISSUE TITLE
Bug with request_info

### ISSUE THREAD

**Issue by MinerChAI** [cgrok/clashroyale#30]
**Describe the bug**
I'm making Discord bot using your API.
When I try to get all the cards I get an exception

**Full Code**
```python
import asyncio

import discord
from discord.ext import commands
import clashroyale

from const import *

bot = commands.Bot(command_prefix='$', description='Бот для MGC', command_not_found='Команды {} не существует', command_has_no_subcommands='У команды {} нет подкоманд')

cr_client = clashroyale.official_api.Client(CR_TOKEN, is_async=True)

@bot.group()
async def clashroyale():
    pass

@clashroyale.command()
async def cards():
    c = await cr_client.get_all_cards()
    await bot.say(c)

bot.run(TOKEN)
```

**Expected behavior**

**Actual behavior**
```
Traceback (most recent call last):
  File "C:\Users\iVan\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "x-wingide-python-shell://102272144/2", line 19, in cards
  File "C:\Users\iVan\AppData\Local\Programs\Python\Python36\lib\site-packages\clashroyale\official_api\client.py", line 215, in _aget_model
    raise e
  File "C:\Users\iVan\AppData\Local\Programs\Python\Python36\lib\site-packages\clashroyale\official_api\client.py", line 208, in _aget_model
    data, cached, ts, resp = await self._request(url, **params)
  File "C:\Users\iVan\AppData\Local\Programs\Python\Python36\lib\site-packages\clashroyale\official_api\client.py", line 157, in _arequest
    return self._raise_for_status(resp, await resp.text())
  File "C:\Users\iVan\AppData\Local\Programs\Python\Python36\lib\site-packages\clashroyale\official_api\client.py", line 125, in _raise_for_status
    log.debug(self.REQUEST_LOG.format(method=method or resp.request_info.method, url=resp.url, text=text, status=code))
AttributeError: 'ClientResponse' object has no attribute 'request_info'
```

**Additional context**

**Comment by fourjr** [comment]
Can you run this command? `python -c print(__import__('clashroyale').__version__)`

**Comment by MinerChAI** [comment]
> Can you run this command? `python -c print(__import__('clashroyale').__version__)`

v4.0.1

**Comment by fourjr** [comment]
Do you still face the bug?

**Comment by MinerChAI** [comment]
No, thx
