### ISSUE TITLE
Prblm of clashroyale,,,,  cog used from - https://github.com/Gr8z/Legend-Cogs

### ISSUE THREAD

**Issue by Begginersz** [cgrok/clashroyale#32]
Exception in command 'save'
Traceback (most recent call last):
  File "lib/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/pokemonfanscool/Red-DiscordBot/cogs/clashroyale.py", line 474, in save
    profiledata = await self.clash.get_player(profiletag)
  File "lib/clashroyale/official_api/client.py", line 215, in _aget_model
    raise e
  File "lib/clashroyale/official_api/client.py", line 208, in _aget_model
    data, cached, ts, resp = await self._request(url, **params)
  File "lib/clashroyale/official_api/client.py", line 157, in _arequest
    return self._raise_for_status(resp, await resp.text())
  File "lib/clashroyale/official_api/client.py", line 125, in _raise_for_status
    log.debug(self.REQUEST_LOG.format(method=method or resp.request_info.method, url=resp.url, text=text, status=code))
AttributeError: 'ClientResponse' object has no attribute 'request_info'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "lib/discord/ext/commands/bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "lib/discord/ext/commands/core.py", line 374, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "lib/discord/ext/commands/core.py", line 54, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'ClientResponse' object has no attribute 'request_info'

**Comment by Begginersz** [comment]
plz reply as soon as possible. - Cgrok

**Comment by gogaz** [comment]
Please edit your issue and follow the given pattern to give more context
